import {connected,session,login,logout,rows,insert,patch,upload,videoURL} from './api.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demoArticles=[
 {id:'demo-1',title:'Kenapa harga yang kita lihat di checkout bisa berubah?',source_name:'Contoh editorial',score:86,body:'Data ilustrasi untuk mencoba tampilan. Hubungkan Supabase untuk mengambil berita sungguhan.',published_at:new Date().toISOString()},
 {id:'demo-2',title:'Di balik bisnis game gratis: siapa sebenarnya yang membayar?',source_name:'Contoh editorial',score:79,body:'Data ilustrasi, bukan berita terkini.',published_at:new Date().toISOString()},
 {id:'demo-3',title:'Satu klik, banyak konsekuensi. Cara kerja tautan penipuan.',source_name:'Contoh editorial',score:72,body:'Data ilustrasi, bukan berita terkini.',published_at:new Date().toISOString()}
];
let page='radar', data={articles:[],jobs:[],assets:[],renders:[],sources:[]}, query='',selected=null,busy=false;
const nav=[['radar','◎','News radar'],['studio','▣','Content studio'],['queue','↗','Production queue'],['assets','▤','Gameplay library'],['sources','◈','News sources'],['setup','⚙','Setup & connections']];
const demo=!connected;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),5000);}
const time=s=>new Date(s).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'});
function shell(){
 $('#app').innerHTML=`<aside><a class="brand" href="#radar"><span class="brandmark">Z<span>↗</span></span><span>GEN-Z<small>NEWS CONTENT FACTORY</small></span></a><div class="workspace">WORKSPACE <span>01</span></div><nav>${nav.map(([id,icon,label])=>`<button data-nav="${id}" class="${page===id?'active':''}"><span>${icon}</span>${label}${id==='queue'?`<b>${data.jobs.filter(j=>j.status==='queued'||j.status==='running').length}</b>`:''}</button>`).join('')}</nav><div class="aside-bottom"><span class="status-dot"></span>${demo?'Preview workspace':'Supabase connected'}<p>${demo?'Explore the factory. Connect to produce.':'Private data · Asia/Jakarta'}</p>${!demo?'<button id="logout">Keluar akun</button>':''}</div></aside><main><header><div>WORKSPACE <span>/</span> ${escape(nav.find(n=>n[0]===page)?.[2])}</div><span class="pill">${demo?'DEMO • DATA ILUSTRASI':'CONNECTED'}</span></header><div id="content"></div><footer>GEN-Z NEWS CONTENT FACTORY <span>Make the news make sense.</span></footer></main>`;
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;location.hash=page;render();});
 $('#logout')?.addEventListener('click',async()=>{await logout();location.reload();});
}
function heading(k,title,desc,action=''){return `<div class="heading"><div><div class="eyebrow">${k}</div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`;}
function guard(){if(demo){toast('Ini mode demo. Hubungkan Supabase di Setup untuk produksi sungguhan.');return false;}return true;}
async function task(fn){if(busy)return;busy=true;try{await fn();}catch(e){toast(e.message);}finally{busy=false;}}
async function refresh(){if(!demo&&session()){const entries=await Promise.all(Object.keys(data).map(async k=>[k,await rows(k)]));data=Object.fromEntries(entries);}else if(demo)data.articles=demoArticles;}
function assetOptions(){return data.assets.map(a=>`<option value="${a.id}">${escape(a.name)}</option>`).join('');}
function render(){shell();const c=$('#content');
 if(page==='radar'){
 c.innerHTML=heading('THE NEWSROOM','Catch the story.<br><em>Start the conversation.</em>','Pilih berita, tentukan angle, biarkan factory merakit videonya.','<button class="primary" id="scan">↻ Cek berita terbaru</button>')+`<div class="stats"><article><small>BERITA TERKUMPUL</small><strong>${data.articles.length.toString().padStart(2,'0')}</strong><span>${demo?'Contoh tampilan':'100 berita terbaru'}</span></article><article><small>DALAM PRODUKSI</small><strong>${data.jobs.filter(j=>['queued','running'].includes(j.status)).length.toString().padStart(2,'0')}</strong><span>Script → audio → render</span></article><article><small>VIDEO SELESAI</small><strong>${data.renders.length.toString().padStart(2,'0')}</strong><span>Siap preview & download</span></article></div><div class="section-title"><h2>On your radar <span>↗</span></h2><input id="search" type="search" placeholder="Cari judul atau portal…" value="${escape(query)}" aria-label="Cari berita"></div><div id="articles"></div><div class="note"><b>Latest ≠ viral.</b> Skor adalah prioritas editorial berbasis kebaruan dan cakupan, bukan angka views TikTok.</div>`;
 $('#search').oninput=e=>{query=e.target.value;articleCards();};articleCards();
 $('#scan').onclick=()=>task(async()=>{if(!guard())return;if(!data.sources.some(s=>s.enabled))throw new Error('Tambahkan dan aktifkan RSS di News sources terlebih dahulu.');await insert('jobs',{kind:'scan'});toast('Scan masuk antrean. Worker akan mengambil berita.');await refresh();render();});
 } else if(page==='studio'){
 const a=data.articles.find(a=>a.id===selected)||data.articles[0];
 c.innerHTML=heading('CREATE SOMETHING WORTH WATCHING','Content studio','Dari berita menjadi cerita singkat, lengkap dengan suara dan subtitle.')+`<div class="studio"><div class="panel"><h2>01 / Pilih cerita</h2><label>Berita<select id="article">${data.articles.map(x=>`<option value="${x.id}" ${a?.id===x.id?'selected':''}>${escape(x.title)}</option>`).join('')}</select></label><p class="muted">${escape(a?.source_name||'Belum ada berita. Tambahkan artikel di bawah.')}</p><div class="excerpt">${escape(a?.body||'')}</div><h2>02 / Atur produksi</h2><div class="twocol"><label>Suara AI<select id="voice"><option value="alloy">Alloy</option><option value="coral">Coral</option><option value="onyx">Onyx</option><option value="nova">Nova</option></select></label><label>Gameplay<select id="asset"><option value="">Pilih footage milik lu</option>${assetOptions()}</select></label></div><p class="muted">Bahasa Indonesia · Target 30–60 detik · MP4 1080 × 1920 · Subtitle sinkron audio</p><button id="generate" class="primary wide">✦ Generate video</button><details><summary>Tambah artikel manual</summary><form id="manual"><label>Judul<input name="title" maxlength="300" required></label><label>Nama portal<input name="source_name" required></label><label>URL sumber<input name="source_url" type="url" pattern="https://.*" required></label><label>Tanggal terbit (WIB)<input name="published_at" type="datetime-local" required></label><label>Isi artikel yang boleh digunakan<textarea name="body" minlength="300" maxlength="20000" rows="6" required></textarea></label><button class="secondary">Simpan artikel</button></form></details></div><div><div class="phone"><div class="phone-top">GEN-Z <span>NEWS IN A MINUTE</span></div><div class="preview-grid"><div class="track"></div><span>GAMEPLAY PREVIEW</span></div><div class="phone-caption">BERITA HARI INI.<br><mark>BAHASA KITA.</mark></div><div class="phone-bottom">AI narration · Sumber dicantumkan</div></div><p class="preview-label">Ilustrasi layout • bukan video hasil render</p></div></div>`;
 $('#article').onchange=e=>{selected=e.target.value;render();};
 $('#generate').onclick=()=>task(async()=>{if(!guard())return;const article=$('#article').value,asset=$('#asset').value;if(!article||!asset)throw new Error('Pilih berita dan upload gameplay dahulu.');await insert('jobs',{kind:'produce',article_id:article,asset_id:asset,voice:$('#voice').value});page='queue';await refresh();render();toast('Produksi masuk antrean.');});
 $('#manual').onsubmit=e=>{e.preventDefault();task(async()=>{if(!guard())return;const d=Object.fromEntries(new FormData(e.target));d.published_at=new Date(d.published_at+':00+07:00').toISOString();d.fingerprint='manual:'+crypto.randomUUID();await insert('articles',d);await refresh();render();toast('Artikel tersimpan.');});};
 } else if(page==='queue'){
 c.innerHTML=heading('THE ASSEMBLY LINE','Production queue','Lihat progres, sumber error, dan hasil video di satu tempat.','<button class="secondary" id="refresh">↻ Refresh</button>')+`<div class="pipeline">${['Berita','Script','Dubbing','Caption','Render','MP4'].map((s,i)=>`<div><span>0${i+1}</span>${s}</div>`).join('')}</div><div class="panel">${data.jobs.length?data.jobs.map(j=>`<div class="job"><div><span class="badge ${escape(j.status)}">${escape(j.status)}</span><h3>${escape(j.kind==='scan'?'Scan portal berita':data.articles.find(a=>a.id===j.article_id)?.title||'Video produksi')}</h3><p>${escape(j.stage)} · ${time(j.created_at)}</p>${j.error?`<p class="error">${escape(j.error)}</p>`:''}${j.result?`<p class="muted">${escape(JSON.stringify(j.result))}</p>`:''}</div>${j.status==='failed'?`<button class="secondary" data-retry="${j.id}">Coba lagi</button>`:''}</div>`).join(''):'<div class="empty">Belum ada produksi.<p>Pilih berita di Content studio untuk mulai.</p></div>'}</div><h2 class="output-title">Finished cuts</h2><div class="cards">${data.renders.map(r=>`<article class="panel"><span class="eyebrow">MP4 · ${Math.round(r.duration_seconds)}s</span><h3>${escape(r.title)}</h3><button class="primary" data-video="${r.id}">Buka video ↗</button><details><summary>Script & sumber</summary><p>${escape(r.script?.sentences?.map(s=>s.text).join(" ")||"")}</p><p>${escape(r.script?.source_name||"")} · ${escape(r.script?.source_url||"")}</p><p>${escape(r.script?.post_caption||"")}</p></details></article>`).join('')||'<p class="muted">Hasil render akan muncul di sini. Posting TikTok belum diaktifkan.</p>'}</div>`;
 $('#refresh').onclick=()=>task(async()=>{await refresh();render();});
 document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>task(async()=>{const j=data.jobs.find(j=>j.id===b.dataset.retry);await insert('jobs',{kind:j.kind,article_id:j.article_id,asset_id:j.asset_id,voice:j.voice,auto_produce:j.auto_produce});await refresh();render();}));
 document.querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>task(async()=>{const r=data.renders.find(r=>r.id===b.dataset.video);const url=await videoURL(r.storage_path);const dialog=document.createElement('dialog');dialog.innerHTML=`<button class="secondary close">Tutup</button><video controls autoplay></video><p><a target="_blank" rel="noopener">Buka / simpan MP4 ↗</a></p>`;dialog.querySelector('video').src=url;dialog.querySelector('a').href=url;document.body.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();}));
 } else if(page==='assets'){
 c.innerHTML=heading('YOUR VISUAL SIGNATURE','Gameplay library','Upload footage yang akan dipilih saat video diproduksi.')+`<div class="panel"><form id="upload"><label>Nama footage<input name="name" placeholder="Minecraft parkour — take 01" required maxlength="120"></label><label class="upload-area">↑ Pilih video MP4 <small>Maksimal 50 MB · portrait disarankan</small><input type="file" name="file" accept="video/mp4" required></label><label class="check"><input type="checkbox" required>Saya punya izin menggunakan footage ini untuk konten.</label><button class="primary">Upload gameplay</button></form></div><div class="cards">${data.assets.map(a=>`<article class="panel"><div class="asset-icon">▷</div><h3>${escape(a.name)}</h3><p class="muted">${time(a.created_at)}</p></article>`).join('')}</div>`;
 $('#upload').onsubmit=e=>{e.preventDefault();task(async()=>{if(!guard())return;const d=new FormData(e.target),file=d.get('file');if(file.size>50*1024*1024||!file.name.toLowerCase().endsWith('.mp4'))throw new Error('Gunakan MP4 maksimal 50 MB.');toast('Mengunggah footage…');const storage_path=await upload(file);await insert('assets',{name:d.get('name'),storage_path,rights_confirmed:true});await refresh();render();toast('Gameplay siap digunakan.');});};
 } else if(page==='sources'){
 c.innerHTML=heading('KEEP YOUR SOURCES CLOSE','News sources','Hubungkan RSS yang sudah diuji. Detik, Kompas, dan Kumparan perlu URL feed yang aktif serta akses yang sesuai.')+`<div class="panel"><form id="source"><div class="twocol"><label>Nama portal<input name="name" placeholder="Nama portal" maxlength="120" required></label><label>RSS URL<input name="feed_url" type="url" pattern="https://.*" placeholder="https://portal.tld/rss" required></label></div><label class="check"><input type="checkbox" required>Sumber ini boleh diakses otomatis dan digunakan untuk rangkuman.</label><button class="primary">Tambahkan sumber</button></form></div><div class="panel source-list">${data.sources.map(s=>`<div class="job"><div><h3>${escape(s.name)}</h3><p>${escape(s.feed_url)}</p><p class="muted">${s.last_checked?'Terakhir dicek '+time(s.last_checked):'Belum diuji oleh worker'}</p>${s.last_error?`<p class="error">${escape(s.last_error)}</p>`:''}</div><button class="secondary" data-toggle="${s.id}">${s.enabled?'Nonaktifkan':'Aktifkan'}</button></div>`).join('')||'<p class="muted">Belum ada sumber. Feed pendek akan dilewati jika teksnya tidak cukup untuk script.</p>'}</div><div class="panel"><h2>Scan → otomatis jadi video</h2><p>Ambil berita baru lalu antrekan maksimal 3 berita berteks cukup yang belum pernah diproduksi. Tetap mengikuti batas harian worker.</p><label>Gameplay<select id="autoasset"><option value="">Pilih gameplay</option>${assetOptions()}</select></label><button id="autoscan" class="primary">Jalankan factory</button></div>`;
 $('#source').onsubmit=e=>{e.preventDefault();task(async()=>{if(!guard())return;await insert('sources',{...Object.fromEntries(new FormData(e.target)),enabled:true});await refresh();render();});};
 document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>task(async()=>{const s=data.sources.find(s=>s.id===b.dataset.toggle);await patch('sources',s.id,{enabled:!s.enabled});await refresh();render();}));
 $('#autoscan').onclick=()=>task(async()=>{if(!guard())return;if(!$('#autoasset').value)throw new Error('Pilih gameplay dahulu.');if(!data.sources.some(s=>s.enabled))throw new Error('Aktifkan minimal satu sumber.');await insert('jobs',{kind:'scan',auto_produce:true,asset_id:$('#autoasset').value});page='queue';await refresh();render();});
 } else {
 c.innerHTML=heading('SET THE FACTORY IN MOTION','Setup & connections','Sambungkan sekali. Jalankan produksi dari dashboard.')+`<div class="setup-grid">${[['01','Supabase',connected?'Konfigurasi frontend terpasang':'Belum terhubung','Buat project baru, jalankan migration SQL, buat user, lalu tambahkan ke factory_members.'],['02','Netlify','Konfigurasi repo siap','Import repo, pilih branch feature/content-factory-v1, build npm run build, publish dist.'],['03','OpenAI + worker','Perlu setup server','Jalankan worker Docker dengan API key, service role key, dan WORKER_OWNER_ID. Status job mengonfirmasi eksekusi.'],['04','TikTok','Belum diintegrasikan','Versi ini menghasilkan MP4 untuk review dan upload manual.']].map(([n,t,s,d])=>`<article class="panel"><span class="eyebrow">CONNECTION ${n}</span><h2>${t}</h2><span class="badge">${s}</span><p>${d}</p></article>`).join('')}</div><div class="note">Panduan lengkap ada di repo: <b>docs/SETUP.md</b>. API key OpenAI dan Supabase service role hanya di worker, bukan di frontend.</div>`;
 }
}
function articleCards(){const items=data.articles.filter(a=>(a.title+' '+a.source_name).toLowerCase().includes(query.toLowerCase()));$('#articles').innerHTML=items.length?items.map((a,i)=>`<article class="story"><div class="story-index">${String(i+1).padStart(2,'0')}</div><div class="story-main"><div class="story-meta">${escape(a.source_name)} <span>•</span> ${time(a.published_at)}</div><h3>${escape(a.title)}</h3><span class="small-label">${demo?'ILUSTRASI':'SUMBER TERSIMPAN'}</span></div><div class="score"><strong>${a.score}</strong><small>PRIORITY</small></div><button class="secondary" data-story="${a.id}">Buat video ↗</button></article>`).join(''):'<div class="panel empty">Belum ada berita yang cocok.<p>Jalankan scan atau tambah artikel manual di Content studio.</p></div>';document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{selected=b.dataset.story;page='studio';render();});}
function loginScreen(){ $('#app').innerHTML=`<div class="login"><div class="brandmark">Z↗</div><div class="eyebrow">GEN-Z NEWS CONTENT FACTORY</div><h1>Your next story<br>starts here.</h1><form id="login"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="primary wide">Masuk workspace</button></form><p>Akun dibuat melalui Supabase Authentication.</p></div>`;$('#login').onsubmit=e=>{e.preventDefault();task(async()=>{const d=new FormData(e.target);await login(d.get('email'),d.get('password'));await refresh();render();});};}
if(connected&&!session())loginScreen();else {try{await refresh();}catch(e){toast(e.message);}page=nav.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'radar';render();}
setInterval(async()=>{if(!demo&&session()&&page==='queue'&&!busy&&!document.querySelector('dialog')){try{await refresh();render();}catch(e){toast(e.message);}}},10000);
